//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RaGae.App.Lamp.Forms.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class StringResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RaGae.App.Lamp.Forms.Resources.StringResource", typeof(StringResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to G.Raf.
        /// </summary>
        internal static string Author {
            get {
                return ResourceManager.GetString("Author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Somebody needs your attention!.
        /// </summary>
        internal static string BalloonTipText {
            get {
                return ResourceManager.GetString("BalloonTipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lamp Information.
        /// </summary>
        internal static string BalloonTipTitle {
            get {
                return ResourceManager.GetString("BalloonTipTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to G.Raf^engineering.
        /// </summary>
        internal static string Company {
            get {
                return ResourceManager.GetString("Company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection Error.
        /// </summary>
        internal static string ConnectionError {
            get {
                return ResourceManager.GetString("ConnectionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection Established.
        /// </summary>
        internal static string ConnectionEstablished {
            get {
                return ResourceManager.GetString("ConnectionEstablished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color.
        /// </summary>
        internal static string FormConfiguration_buttonColor {
            get {
                return ResourceManager.GetString("FormConfiguration_buttonColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setup.
        /// </summary>
        internal static string FormConfiguration_buttonSetUp {
            get {
                return ResourceManager.GetString("FormConfiguration_buttonSetUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Config.
        /// </summary>
        internal static string FormConfiguration_groupBoxConfiguration {
            get {
                return ResourceManager.GetString("FormConfiguration_groupBoxConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alpha.
        /// </summary>
        internal static string FormConfiguration_labelAlpha {
            get {
                return ResourceManager.GetString("FormConfiguration_labelAlpha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        internal static string FormConfiguration_labelTime {
            get {
                return ResourceManager.GetString("FormConfiguration_labelTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration.
        /// </summary>
        internal static string FormConfiguration_Text {
            get {
                return ResourceManager.GetString("FormConfiguration_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frame.
        /// </summary>
        internal static string FormConnection_groupBoxFrame {
            get {
                return ResourceManager.GetString("FormConnection_groupBoxFrame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serial Port.
        /// </summary>
        internal static string FormConnection_groupBoxSerial {
            get {
                return ResourceManager.GetString("FormConnection_groupBoxSerial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @.
        /// </summary>
        internal static string FormConnection_labelAt {
            get {
                return ResourceManager.GetString("FormConnection_labelAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Baud.
        /// </summary>
        internal static string FormConnection_labelBaud {
            get {
                return ResourceManager.GetString("FormConnection_labelBaud", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Databits.
        /// </summary>
        internal static string FormConnection_labelDataBits {
            get {
                return ResourceManager.GetString("FormConnection_labelDataBits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parity.
        /// </summary>
        internal static string FormConnection_labelParity {
            get {
                return ResourceManager.GetString("FormConnection_labelParity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port:.
        /// </summary>
        internal static string FormConnection_labelPort {
            get {
                return ResourceManager.GetString("FormConnection_labelPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stopbit(s).
        /// </summary>
        internal static string FormConnection_labelStopbits {
            get {
                return ResourceManager.GetString("FormConnection_labelStopbits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection.
        /// </summary>
        internal static string FormConnection_Text {
            get {
                return ResourceManager.GetString("FormConnection_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable system notification!.
        /// </summary>
        internal static string FormMain_checkBoxNotification {
            get {
                return ResourceManager.GetString("FormMain_checkBoxNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration.
        /// </summary>
        internal static string FormMain_configurationToolStripMenuItem {
            get {
                return ResourceManager.GetString("FormMain_configurationToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection.
        /// </summary>
        internal static string FormMain_connectionToolStripMenuItem {
            get {
                return ResourceManager.GetString("FormMain_connectionToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mode.
        /// </summary>
        internal static string FormMain_groupBoxMode {
            get {
                return ResourceManager.GetString("FormMain_groupBoxMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string FormMain_groupBoxStatus {
            get {
                return ResourceManager.GetString("FormMain_groupBoxStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.
        /// </summary>
        internal static string FormMain_groupBoxSystem {
            get {
                return ResourceManager.GetString("FormMain_groupBoxSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        internal static string FormMain_helpToolStripMenuItem {
            get {
                return ResourceManager.GetString("FormMain_helpToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ?.
        /// </summary>
        internal static string FormMain_labelMode {
            get {
                return ResourceManager.GetString("FormMain_labelMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string FormMain_labelStatus {
            get {
                return ResourceManager.GetString("FormMain_labelStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        internal static string FormMain_messageToolStripMenuItem {
            get {
                return ResourceManager.GetString("FormMain_messageToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quit.
        /// </summary>
        internal static string FormMain_quitToolStripMenuItem {
            get {
                return ResourceManager.GetString("FormMain_quitToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string FormMain_saveToolStripMenuItem {
            get {
                return ResourceManager.GetString("FormMain_saveToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        internal static string FormMain_startToolStripMenuItem {
            get {
                return ResourceManager.GetString("FormMain_startToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.
        /// </summary>
        internal static string FormMain_systemToolStripMenuItem {
            get {
                return ResourceManager.GetString("FormMain_systemToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lamp Control.
        /// </summary>
        internal static string FormMain_Text {
            get {
                return ResourceManager.GetString("FormMain_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check for Updates.
        /// </summary>
        internal static string FormMain_updateToolStripMenuItem {
            get {
                return ResourceManager.GetString("FormMain_updateToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        internal static string FormMain_versionToolStripMenuItem {
            get {
                return ResourceManager.GetString("FormMain_versionToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification.
        /// </summary>
        internal static string FormMessage_groupBoxNotification {
            get {
                return ResourceManager.GetString("FormMessage_groupBoxNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text:.
        /// </summary>
        internal static string FormMessage_labelText {
            get {
                return ResourceManager.GetString("FormMessage_labelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time:.
        /// </summary>
        internal static string FormMessage_labelTime {
            get {
                return ResourceManager.GetString("FormMessage_labelTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title:.
        /// </summary>
        internal static string FormMessage_labelTitle {
            get {
                return ResourceManager.GetString("FormMessage_labelTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        internal static string FormMessage_Text {
            get {
                return ResourceManager.GetString("FormMessage_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assembly.
        /// </summary>
        internal static string FormVersion_groupBoxAssembly {
            get {
                return ResourceManager.GetString("FormVersion_groupBoxAssembly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creator.
        /// </summary>
        internal static string FormVersion_groupBoxCreator {
            get {
                return ResourceManager.GetString("FormVersion_groupBoxCreator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Package.
        /// </summary>
        internal static string FormVersion_groupBoxPackage {
            get {
                return ResourceManager.GetString("FormVersion_groupBoxPackage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author:.
        /// </summary>
        internal static string FormVersion_labelAuthor {
            get {
                return ResourceManager.GetString("FormVersion_labelAuthor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ?.
        /// </summary>
        internal static string FormVersion_labelAuthorRef {
            get {
                return ResourceManager.GetString("FormVersion_labelAuthorRef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company:.
        /// </summary>
        internal static string FormVersion_labelCompany {
            get {
                return ResourceManager.GetString("FormVersion_labelCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ?.
        /// </summary>
        internal static string FormVersion_labelCompanyRef {
            get {
                return ResourceManager.GetString("FormVersion_labelCompanyRef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link:.
        /// </summary>
        internal static string FormVersion_labelLink {
            get {
                return ResourceManager.GetString("FormVersion_labelLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ?.
        /// </summary>
        internal static string FormVersion_labelLinkRef {
            get {
                return ResourceManager.GetString("FormVersion_labelLinkRef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name:.
        /// </summary>
        internal static string FormVersion_labelName {
            get {
                return ResourceManager.GetString("FormVersion_labelName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ?.
        /// </summary>
        internal static string FormVersion_labelNameRef {
            get {
                return ResourceManager.GetString("FormVersion_labelNameRef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Protocol:.
        /// </summary>
        internal static string FormVersion_labelProtocol {
            get {
                return ResourceManager.GetString("FormVersion_labelProtocol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ?.
        /// </summary>
        internal static string FormVersion_labelProtocolRef {
            get {
                return ResourceManager.GetString("FormVersion_labelProtocolRef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version:.
        /// </summary>
        internal static string FormVersion_labelVersion {
            get {
                return ResourceManager.GetString("FormVersion_labelVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ?.
        /// </summary>
        internal static string FormVersion_labelVersionRef {
            get {
                return ResourceManager.GetString("FormVersion_labelVersionRef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        internal static string FormVersion_Text {
            get {
                return ResourceManager.GetString("FormVersion_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Global Exception.
        /// </summary>
        internal static string GlobalException {
            get {
                return ResourceManager.GetString("GlobalException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        internal static string Information {
            get {
                return ResourceManager.GetString("Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://github.com/sunriax.
        /// </summary>
        internal static string Link {
            get {
                return ResourceManager.GetString("Link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings saved successfully!.
        /// </summary>
        internal static string SettingsSaved {
            get {
                return ResourceManager.GetString("SettingsSaved", resourceCulture);
            }
        }
    }
}
